spring:
  application:
    name: milestory-backend
  profiles:
    default: local
  datasource:
    url: ${MILESTORY_DB_URL:jdbc:postgresql://localhost:5432/milestory}
    username: ${MILESTORY_DB_USERNAME:milestory}
    password: ${MILESTORY_DB_PASSWORD:milestory}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml