spring:
  datasource:
    url: jdbc:postgresql://${MILESTORY_DB_HOST:localhost}:${MILESTORY_DB_PORT:5432}/${MILESTORY_DB_NAME:}
    username: ${MILESTORY_DB_USERNAME:milestory}
    password: ${MILESTORY_DB_PASSWORD:milestory}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml