/**
 * Milestory API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetFoundationStatus503Response { 
    headline: string;
    summary: string;
    mode: GetFoundationStatus503Response.ModeEnum;
    generatedAt: string;
    notes: Array<string>;
}
export namespace GetFoundationStatus503Response {
    export const ModeEnum = {
        Ready: 'ready',
        Empty: 'empty',
        Degraded: 'degraded'
    } as const;
    export type ModeEnum = typeof ModeEnum[keyof typeof ModeEnum];
}


