# The version 3.1.2 needs to be maintained due to issues with the openapi-generator-cli that doesn't work properly with $refs
openapi: 3.1.2
info:
  title: Milestory API
  description: An application where your goals find their story
  version: v1
servers:
  - url: http://localhost:8080
    description: URL for local development

paths:
  /api/v1/status:
    $ref: './paths/status.yaml'
  /api/v1/goal-categories:
    $ref: './paths/goal-categories.yaml'
  /api/v1/goal-plans/previews:
    $ref: './paths/goal-plans-preview.yaml'
  /api/v1/goals:
    $ref: './paths/goals.yaml'
  /api/v1/goals/{goalId}:
    $ref: './paths/goal-by-id.yaml#/GoalByIdPath'
  /api/v1/goals/{goalId}/progress-entries:
    $ref: './paths/goal-by-id.yaml#/GoalProgressEntriesPath'
  /api/v1/goals/{goalId}/archive:
    $ref: './paths/goal-by-id.yaml#/GoalArchivePath'
  /api/v1/goals/{goalId}/restore:
    $ref: './paths/goal-by-id.yaml#/GoalRestorePath'
