# The version 3.1.2 needs to be maintained due to issues with the openapi-generator-cli that doesn't work properly with $refs
openapi: 3.1.2
info:
  title: Milestory API
  description: An application where your goals find their story
  version: v1
servers:
  - url: http://localhost:8080
    description: URL for local development

paths:
  /api/v1/status:
    $ref: './paths/status.yaml'
